<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AgriEncuestadoresInsumosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $encuestadores = [
            [
                'dni' => '12345678',
                'nombres' => 'Juan Carlos',
                'apellido_paterno' => 'García',
                'apellido_materno' => 'López',
                'fecha_nacimiento' => '1990-05-15',
                'genero' => 'M',
                'telefono' => '987654321',
                'email' => 'juan.garcia@dra.gob.pe',
                'direccion' => 'Av. Los Agricultores 123, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Arequipa',
                'distrito_asignado' => 'Cercado',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'maquinaria,fertilizantes',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-01-15',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-01-20',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '23456789',
                'nombres' => 'María Elena',
                'apellido_paterno' => 'Rodríguez',
                'apellido_materno' => 'Pérez',
                'fecha_nacimiento' => '1988-08-22',
                'genero' => 'F',
                'telefono' => '987654322',
                'email' => 'maria.rodriguez@dra.gob.pe',
                'direccion' => 'Calle Los Incas 456, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Camaná',
                'distrito_asignado' => null,
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'agroquimicos,fertilizantes',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-02-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-02-05',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '34567890',
                'nombres' => 'Pedro Antonio',
                'apellido_paterno' => 'Mamani',
                'apellido_materno' => 'Quispe',
                'fecha_nacimiento' => '1992-03-10',
                'genero' => 'M',
                'telefono' => '987654323',
                'email' => 'pedro.mamani@dra.gob.pe',
                'direccion' => 'Jr. Puno 789, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Caylloma',
                'distrito_asignado' => 'Chivay',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'maquinaria,transporte',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-03-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-03-10',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '45678901',
                'nombres' => 'Ana Lucía',
                'apellido_paterno' => 'Flores',
                'apellido_materno' => 'Chávez',
                'fecha_nacimiento' => '1991-11-30',
                'genero' => 'F',
                'telefono' => '987654324',
                'email' => 'ana.flores@dra.gob.pe',
                'direccion' => 'Av. La Marina 234, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Islay',
                'distrito_asignado' => 'Mollendo',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'fertilizantes,agroquimicos',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-03-15',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-03-20',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '56789012',
                'nombres' => 'Luis Fernando',
                'apellido_paterno' => 'Puma',
                'apellido_materno' => 'Ccosi',
                'fecha_nacimiento' => '1989-07-18',
                'genero' => 'M',
                'telefono' => '987654325',
                'email' => 'luis.puma@dra.gob.pe',
                'direccion' => 'Calle Bolognesi 567, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Condesuyos',
                'distrito_asignado' => 'Chuquibamba',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'transporte,maquinaria',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-04-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-04-05',
                'certificado_senasa' => false,
                'created_by' => 1,
            ],
            [
                'dni' => '67890123',
                'nombres' => 'Rosa María',
                'apellido_paterno' => 'Huamán',
                'apellido_materno' => 'Vargas',
                'fecha_nacimiento' => '1993-09-25',
                'genero' => 'F',
                'telefono' => '987654326',
                'email' => 'rosa.huaman@dra.gob.pe',
                'direccion' => 'Av. Ejército 890, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'La Unión',
                'distrito_asignado' => 'Cotahuasi',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'agroquimicos,transporte',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-05-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-05-10',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '78901234',
                'nombres' => 'Carlos Alberto',
                'apellido_paterno' => 'Salas',
                'apellido_materno' => 'Medina',
                'fecha_nacimiento' => '1987-12-05',
                'genero' => 'M',
                'telefono' => '987654327',
                'email' => 'carlos.salas@dra.gob.pe',
                'direccion' => 'Jr. Miraflores 123, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Castilla',
                'distrito_asignado' => 'Aplao',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'maquinaria,fertilizantes,agroquimicos',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-06-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-06-05',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
            [
                'dni' => '89012345',
                'nombres' => 'Sofía Isabel',
                'apellido_paterno' => 'Cárdenas',
                'apellido_materno' => 'Torres',
                'fecha_nacimiento' => '1994-04-12',
                'genero' => 'F',
                'telefono' => '987654328',
                'email' => 'sofia.cardenas@dra.gob.pe',
                'direccion' => 'Calle Real 456, Arequipa',
                'region_asignada' => 'Arequipa',
                'provincia_asignada' => 'Arequipa',
                'distrito_asignado' => 'Yanahuara',
                'cargo' => 'Encuestador SIEA',
                'especializacion' => 'fertilizantes,agroquimicos,transporte',
                'usuario_id' => null,
                'fecha_ingreso' => '2024-07-01',
                'fecha_salida' => null,
                'estado' => 'activo',
                'motivo_inactividad' => null,
                'fecha_capacitacion' => '2024-07-10',
                'certificado_senasa' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($encuestadores as $encuestador) {
            DB::table('agri_encuestadores_insumos')->insert(array_merge($encuestador, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ Se insertaron ' . count($encuestadores) . ' encuestadores');
    }
}
