<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgriFertilizantesInsumosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fertilizantes = [
            // NITROGENADOS
            [
                'nombre_comercial' => 'Nitrato de Amonio',
                'nombre_generico' => 'Nitrato de Amonio',
                'tipo' => 'nitrogenado',
                'codigo' => 'FERT-NA',
                'formula' => '33-0-0',
                'porcentaje_nitrogeno' => 33.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante nitrogenado de rápida acción',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Sulfato de Amonio',
                'nombre_generico' => 'Sulfato de Amonio',
                'tipo' => 'nitrogenado',
                'codigo' => 'FERT-SA',
                'formula' => '21-0-0',
                'porcentaje_nitrogeno' => 21.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante nitrogenado con azufre',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Urea',
                'nombre_generico' => 'Urea',
                'tipo' => 'nitrogenado',
                'codigo' => 'FERT-UR',
                'formula' => '46-0-0',
                'porcentaje_nitrogeno' => 46.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante nitrogenado de alta concentración',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Nitro S',
                'nombre_generico' => 'Nitrato con Azufre',
                'tipo' => 'nitrogenado',
                'codigo' => 'FERT-NS',
                'formula' => '26-0-0',
                'porcentaje_nitrogeno' => 26.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante nitrogenado con azufre incorporado',
                'activo' => true,
            ],

            // FOSFATADOS
            [
                'nombre_comercial' => 'Fosfato Diamónico',
                'nombre_generico' => 'DAP',
                'tipo' => 'fosfatado',
                'codigo' => 'FERT-DAP',
                'formula' => '18-46-0',
                'porcentaje_nitrogeno' => 18.00,
                'porcentaje_fosforo' => 46.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante fosfatado con nitrógeno',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Superfosfato Triple',
                'nombre_generico' => 'Superfosfato Triple',
                'tipo' => 'fosfatado',
                'codigo' => 'FERT-SFT',
                'formula' => '0-46-0',
                'porcentaje_nitrogeno' => 0.00,
                'porcentaje_fosforo' => 46.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante fosfatado concentrado',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Roca Fosfórica',
                'nombre_generico' => 'Roca Fosfórica',
                'tipo' => 'fosfatado',
                'codigo' => 'FERT-RF',
                'formula' => '0-30-0',
                'porcentaje_nitrogeno' => 0.00,
                'porcentaje_fosforo' => 30.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante fosfórico natural de liberación lenta',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Fosfato Monoamónico',
                'nombre_generico' => 'MAP',
                'tipo' => 'fosfatado',
                'codigo' => 'FERT-MAP',
                'formula' => '11-52-0',
                'porcentaje_nitrogeno' => 11.00,
                'porcentaje_fosforo' => 52.00,
                'porcentaje_potasio' => 0.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante fosfatado de alta concentración',
                'activo' => true,
            ],

            // POTÁSICOS
            [
                'nombre_comercial' => 'Cloruro de Potasio',
                'nombre_generico' => 'KCl',
                'tipo' => 'potasico',
                'codigo' => 'FERT-KCL',
                'formula' => '0-0-60',
                'porcentaje_nitrogeno' => 0.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 60.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante potásico concentrado',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Sulfato de Potasio',
                'nombre_generico' => 'K2SO4',
                'tipo' => 'potasico',
                'codigo' => 'FERT-KSO4',
                'formula' => '0-0-50',
                'porcentaje_nitrogeno' => 0.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 50.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante potásico sin cloro',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Nitrato de Potasio',
                'nombre_generico' => 'KNO3',
                'tipo' => 'potasico',
                'codigo' => 'FERT-KNO3',
                'formula' => '13-0-46',
                'porcentaje_nitrogeno' => 13.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 46.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 25.00,
                'descripcion' => 'Fertilizante potásico con nitrógeno nítrico',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Sulfato de Potasio y Magnesio',
                'nombre_generico' => 'Sul-Po-Mag',
                'tipo' => 'potasico',
                'codigo' => 'FERT-SPM',
                'formula' => '0-0-22',
                'porcentaje_nitrogeno' => 0.00,
                'porcentaje_fosforo' => 0.00,
                'porcentaje_potasio' => 22.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante potásico con magnesio y azufre',
                'activo' => true,
            ],

            // COMPUESTOS
            [
                'nombre_comercial' => 'NPK 12-12-12',
                'nombre_generico' => 'Fertilizante Compuesto',
                'tipo' => 'compuesto',
                'codigo' => 'FERT-121212',
                'formula' => '12-12-12',
                'porcentaje_nitrogeno' => 12.00,
                'porcentaje_fosforo' => 12.00,
                'porcentaje_potasio' => 12.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante completo balanceado',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'NPK 15-15-15',
                'nombre_generico' => 'Fertilizante Compuesto',
                'tipo' => 'compuesto',
                'codigo' => 'FERT-151515',
                'formula' => '15-15-15',
                'porcentaje_nitrogeno' => 15.00,
                'porcentaje_fosforo' => 15.00,
                'porcentaje_potasio' => 15.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante completo balanceado concentrado',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'NPK 20-20-20',
                'nombre_generico' => 'Fertilizante Compuesto',
                'tipo' => 'compuesto',
                'codigo' => 'FERT-202020',
                'formula' => '20-20-20',
                'porcentaje_nitrogeno' => 20.00,
                'porcentaje_fosforo' => 20.00,
                'porcentaje_potasio' => 20.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Fertilizante completo de alta concentración',
                'activo' => true,
            ],

            // ABONOS ORGÁNICOS
            [
                'nombre_comercial' => 'Gallinaza',
                'nombre_generico' => 'Estiércol de Gallina',
                'tipo' => 'organico',
                'codigo' => 'FERT-GAL',
                'formula' => '2-2-1',
                'porcentaje_nitrogeno' => 2.00,
                'porcentaje_fosforo' => 2.00,
                'porcentaje_potasio' => 1.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Abono orgánico de estiércol de aves',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Guano de Isla',
                'nombre_generico' => 'Guano de Isla',
                'tipo' => 'organico',
                'codigo' => 'FERT-GUI',
                'formula' => '10-10-2',
                'porcentaje_nitrogeno' => 10.00,
                'porcentaje_fosforo' => 10.00,
                'porcentaje_potasio' => 2.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Abono orgánico natural de alta calidad',
                'activo' => true,
            ],
            [
                'nombre_comercial' => 'Humus de Lombriz',
                'nombre_generico' => 'Vermicompost',
                'tipo' => 'organico',
                'codigo' => 'FERT-HUM',
                'formula' => '1-1-1',
                'porcentaje_nitrogeno' => 1.00,
                'porcentaje_fosforo' => 1.00,
                'porcentaje_potasio' => 1.00,
                'presentacion' => 'saco',
                'peso_presentacion' => 50.00,
                'descripcion' => 'Abono orgánico procesado por lombrices',
                'activo' => true,
            ],
        ];

        foreach ($fertilizantes as $fertilizante) {
            DB::table('agri_fertilizantes_insumos')->insert(array_merge($fertilizante, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✅ Se insertaron ' . count($fertilizantes) . ' fertilizantes');
    }
}
